Repository swiftmumbai/codingProblems, pull requests merged in 2019-11, with the labels that each got.

#1 Solution/1
  ArrayNumsCanAddTo.playground/Contents.swift
  ArrayNumsCanAddTo.playground/contents.xcplayground
  CodingProblems.xcworkspace/contents.xcworkspacedata
  CodingProblems.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Labels: enhancement

#3 added Question #3
  README.md
Labels: new question

#4 added Question #4
  README.md
Labels: new question

#5 added Question #5
  README.md
Labels: question

#6 added question 6
  README.md
Labels: question
